In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print('%d bytes' % (v.size * v.itemsize))

80 bytes


In [ ]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
v = np.arange(10,20)
print(v)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
v = np.arange(10,50)
print(v)
print(type(v))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
<class 'numpy.ndarray'>


In [ ]:
v = np.arange(50)
print(v)
v = v[::-1]
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
v = np.arange(0,20,2)
print(v)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
v = np.arange(9).reshape(3,3)  #two brackets two dimensional data and 3 brackets is 3 dimensional

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,0,0,2,0,0,3,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,6])
print(nz)

In [ ]:
v = np.eye(3)
print(v)

In [ ]:
v = np.eye(5)
print(v)

In [ ]:
v = np.random.random(10)
print(v)

[0.94134101 0.90559802 0.63970183 0.16428866 0.81690364 0.2307081
 0.3002907  0.23500327 0.49149062 0.85286844]


In [ ]:
v = np.random.random((10,10))
print(v)

[[0.85392555 0.4113914  0.11764318 0.66069749 0.73961642 0.93881023
  0.41145804 0.67728544 0.24296246 0.86871279]
 [0.14514242 0.68192787 0.24274048 0.34230517 0.88102468 0.32679753
  0.28770496 0.3332079  0.49678104 0.40072363]
 [0.68355109 0.91798627 0.27975943 0.52247905 0.33426717 0.29989988
  0.75787649 0.6166468  0.2394151  0.51609101]
 [0.66540692 0.29058815 0.19441238 0.60673524 0.68958105 0.58523683
  0.18818319 0.59996598 0.30716478 0.53133343]
 [0.45772095 0.91634463 0.99987872 0.68671732 0.81102313 0.54735481
  0.5337909  0.86079042 0.06855974 0.68087442]
 [0.17143267 0.281667   0.83906352 0.36219189 0.96413222 0.3301228
  0.69776464 0.90336548 0.5365582  0.10494896]
 [0.55913882 0.46161461 0.58508588 0.11675593 0.28976824 0.53717882
  0.23580766 0.84695612 0.73417443 0.16650629]
 [0.46652115 0.72072746 0.15723182 0.46708913 0.26724514 0.81075042
  0.38476124 0.92788393 0.18593182 0.88498377]
 [0.78092751 0.1656269  0.25225542 0.53918319 0.02889404 0.51761977
  0.66803148 

In [ ]:
v = np.random.random((10,10,10))
print(v)

[[[0.79929478 0.22361392 0.38332624 0.48624219 0.19098064 0.07597005
   0.76584571 0.50183874 0.90504388 0.16017747]
  [0.88368035 0.88750605 0.66093914 0.32578063 0.60239241 0.48336789
   0.1680825  0.66838782 0.04943065 0.51188637]
  [0.66139148 0.00351405 0.81045191 0.48282855 0.35222567 0.27161531
   0.61388484 0.14189924 0.15913566 0.08090585]
  [0.99806225 0.0180731  0.46568241 0.88420235 0.39596863 0.51099389
   0.39383127 0.5042096  0.19017747 0.88880101]
  [0.96374646 0.68636614 0.43084248 0.97104087 0.09686615 0.89019798
   0.88790901 0.95127307 0.86377692 0.24028156]
  [0.28322059 0.05555337 0.89000523 0.53963971 0.9928554  0.85886663
   0.31130977 0.62691041 0.64939421 0.83789608]
  [0.80850462 0.67251499 0.60872384 0.45092461 0.18325524 0.26294986
   0.17042715 0.24724889 0.57392134 0.51883165]
  [0.71339097 0.2487108  0.09419603 0.50694236 0.09981418 0.50004339
   0.91641627 0.94972102 0.41870454 0.52430653]
  [0.57585659 0.7063861  0.49989316 0.09739082 0.96856885 0.5375

In [ ]:
v = np.random.random((2,3,4))  #2 set, 3 rows, 4 columns
print(v)

[[[0.777059   0.86855561 0.43190613 0.95602561]
  [0.39863456 0.66281974 0.07532374 0.9431801 ]
  [0.74971498 0.54258612 0.77935276 0.71499972]]

 [[0.03287629 0.59572068 0.55816934 0.43252488]
  [0.22589339 0.74875413 0.18066163 0.55678505]
  [0.5016892  0.44680054 0.12022515 0.50481051]]]


In [ ]:
#matrix of 1's replaced with 0's
v = np.ones((10,10))
print(v)
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#matrix of zeros replaced with 1's
v = np.zeros((10,10))
print(v)
v[1:-1, 1:-1] = 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#padding values with 9, you can pad with any values
v = np.ones((5,5))
print(v)
v = np.pad(v, pad_width=1, mode='constant', constant_values=9)
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9. 9. 9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9. 9. 9.]]


In [ ]:
#anthing that is null (if you see nan then it's null)
np.nan

nan

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
#create a 5x5 matrix with values 1,2,3,4 just below the diagonal

v = np.zeros((5,5))
print(v)
print()
values = [1, 2, 3, 4]
for i in range(1, 5):
    v[i, i - 1] = values[i - 1]
print(v)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
#Alternate method
z = np.diag(1+np.arange(4),k=-1) #skipping last column k=-1
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


August 29th, Tuesday

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Wednesday August 30th

In [ ]:
!pip install pandas     #installing library ! is used to run bash command

In [ ]:
!pip install LightGBM

In [ ]:
!pip install tensorflow

In [ ]:
#Requirement : connected to internet
#pytorch is used for face recognition
!pip install pytorch

  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
ERROR: Could not build wheels for pytorch, which is required to install pyproject.toml-based projects


In [ ]:
import pandas as pd
# https://pandas.pydata.org/

In [ ]:
path = '/Churn_Modelling.csv'
df_ChurnModelling_csv = pd.read_csv(path)
df_ChurnModelling_csv

In [ ]:
!pip install xlwt

In [ ]:
import xlwt

In [ ]:
df_ChurnModelling_csv.to_excel('df_ChurnModelling_xls.xls')

<ipython-input-23-e0ff2608a408>:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df_ChurnModelling_csv.to_excel('df_ChurnModelling_xls.xls')


In [ ]:
df_ChurnModelling_csv.to_excel('df_ChurnModelling_xlsx.xlsx')

In [ ]:
df_ChurnModelling_csv.to_html('df_ChurnModelling_html.html')

In [27]:
df_ChurnModelling_csv.to_json('df_ChurnModelling_json.json')

In [28]:
df_ChurnModelling_csv.to_xml('df_ChurnModelling_xml.xml')

In [ ]:
path_html = '/content/df_ChurnModelling_html.html'
ChurnModelling_html = pd.read_html(path_html)
ChurnModelling_html

In [ ]:
path_xls = '/content/df_ChurnModelling_xls.xls'
ChurnModelling_xls = pd.read_excel(path_xls)
ChurnModelling_xls

In [ ]:
path_xlsx = '/content/df_ChurnModelling_xlsx.xlsx'
ChurnModelling_xlsx = pd.read_excel(path_xlsx)
ChurnModelling_xlsx

In [ ]:
path_xml = '/content/df_ChurnModelling_xml.xml'
ChurnModelling_xml = pd.read_xml(path_xml)
ChurnModelling_xml

In [ ]:
path_json = '/content/df_ChurnModelling_json.json'
ChurnModelling_json = pd.read_json(path_json)
ChurnModelling_json

In [44]:
import pandas as pd

lst1 = [12,23,34,45,56,67,78,89,110]
sr1 = pd.Series(lst1)
sr1, len(sr1), sr1.count(), sr1.ndim, type(sr1), sr1.size, sr1.dtype, sr1.item, sr1.items, sr1.nbytes, sr1.shape   #1D data so result is 1

(0     12
 1     23
 2     34
 3     45
 4     56
 5     67
 6     78
 7     89
 8    110
 dtype: int64,
 9,
 9,
 1,
 pandas.core.series.Series,
 9,
 dtype('int64'),
 <bound method IndexOpsMixin.item of 0     12
 1     23
 2     34
 3     45
 4     56
 5     67
 6     78
 7     89
 8    110
 dtype: int64>,
 <bound method Series.items of 0     12
 1     23
 2     34
 3     45
 4     56
 5     67
 6     78
 7     89
 8    110
 dtype: int64>,
 72,
 (9,))

In [45]:
import pandas as pd

tup1 = (1,2,3,4,5,6,7,8,9)
tup1 = pd.Series(tup1)
tup1, len(tup1), tup1.count(), tup1.ndim, type(tup1), tup1.size, tup1.dtype, tup1.item, tup1.items, tup1.nbytes, tup1.shape

(0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64,
 9,
 9,
 1,
 pandas.core.series.Series,
 9,
 dtype('int64'),
 <bound method IndexOpsMixin.item of 0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64>,
 <bound method Series.items of 0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64>,
 72,
 (9,))

In [ ]:
import pandas as pd

set1 = {1,12,23,'Python','45',45,67}
set1 = pd.Series(set1)
set1, set1.ndim